import { Download, TrendingDown, TrendingUp } from "lucide-react";
import { db } from "@/lib/db";
import { requireUser } from "@/lib/auth/dal";
import { PageHeader } from "@/components/dashboard/page-header";
import { formatCurrency } from "@/lib/utils";

export default async function ReportsPage() {
  const user = await requireUser();
  const products = await db.product.findMany({ where: { organizationId: user.organizationId, isArchived: false }, include: { supplier: { select: { name: true, leadTimeDays: true } } }, orderBy: { quantity: "asc" } });
  const lowStock = products.filter((product) => product.quantity <= product.reorderLevel);
  const inventoryValue = products.reduce((sum, item) => sum + item.quantity * Number(item.costPrice), 0);
  return <><PageHeader eyebrow="Decision support" title="Inventory reports" description="Turn stock records into reorder priorities and exportable evidence." action={<a href="/api/v1/reports/inventory.csv" className="btn btn-primary"><Download className="size-4" />Export CSV</a>} /><section className="grid gap-4 sm:grid-cols-3"><article className="card p-5"><p className="text-sm text-[#68736c]">Inventory value</p><p className="mt-2 text-3xl font-black">{formatCurrency(inventoryValue)}</p></article><article className="card p-5"><p className="text-sm text-[#68736c]">Reorder candidates</p><p className="mt-2 text-3xl font-black">{lowStock.length}</p></article><article className="card p-5"><p className="text-sm text-[#68736c]">Active SKUs</p><p className="mt-2 text-3xl font-black">{products.length}</p></article></section><section className="card mt-6 overflow-hidden"><div className="border-b p-5"><h2 className="font-extrabold">Reorder intelligence</h2><p className="mt-1 text-sm text-[#68736c]">Priority is based on current quantity, reorder level, and supplier lead time.</p></div><div className="divide-y">{lowStock.map((product) => { const recommendation = Math.max(product.reorderLevel * 2 - product.quantity, product.reorderLevel); return <div key={product.id} className="flex flex-col justify-between gap-3 p-5 sm:flex-row sm:items-center"><div className="flex gap-3"><span className={`grid size-9 place-items-center rounded-xl ${product.quantity === 0 ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{product.quantity === 0 ? <TrendingDown className="size-4" /> : <TrendingUp className="size-4" />}</span><div><p className="font-bold">{product.name}</p><p className="text-xs text-[#68736c]">{product.sku} · {product.supplier?.name ?? "No supplier"}</p></div></div><div className="text-sm sm:text-right"><p><strong>{product.quantity}</strong> on hand · reorder at {product.reorderLevel}</p><p className="font-bold text-[#176b45]">Suggested order: {recommendation} units</p></div></div>; })}{!lowStock.length && <p className="p-10 text-center text-sm text-[#68736c]">Nothing needs reordering right now.</p>}</div></section></>;
}
